`holochain_deepkey_dna` crate
holochain/deepkey pull request #18
Opened 2024-03-11 21:43 UTC by maackle

The easiest way to integrate Deepkey into the conductor is to include its bytes directly in the binary. Probably a good way to do this is to publish this new `holochain_deepkey_dna` crate to crates.io, and the `holochain` crate can depend on it. We realistically only support one deepkey version for now, so this tight coupling seems appropriate at this stage. It can be loosened later on.

2024-03-11 22:29 UTC, maackle commented
Maybe this could be separate from the main deepkey cargo workspace

2024-03-14 12:20 UTC, mjbrisebois requested changes
Mostly looks good.  Just curious about a few things

2024-03-14 12:20 UTC, mjbrisebois commented on crates/holochain_deepkey_dna/src/deepkey.dna
I don't think we should include produced binary files in the git repo.  Is there a reason it needs to be in here?

2024-03-14 12:20 UTC, mjbrisebois commented on Cargo.toml
> +# holochain_types = { path = "/home/michael/Holo/chain/crates/holochain_types" }
```suggestion
```

2024-03-14 12:20 UTC, mjbrisebois commented on crates/holochain_deepkey_dna/Cargo.toml
> +    "../../dnas/deepkey.dna"
If we are copying the dna file into the `src` directory, do we still need this reference to the parent location?

2024-03-15 00:45 UTC, maackle commented on crates/holochain_deepkey_dna/src/deepkey.dna
Oops that's a mistake, I meant for it not to be committed. Will rebase and remove it

2024-03-15 00:51 UTC, maackle commented
I rebased to remove the DNA, see if that checks out

2024-03-20 15:22 UTC, mjbrisebois approved these changes

2024-03-20 15:22 UTC, merged